import { Theme, Font, CompanyData } from "./types";

export const THEMES: Theme[] = [
  {
    name: 'Deep Emerald & Gold',
    primary: '#064E3B',
    accent: '#D4AF37',
    paper: '#FFFFFF',
    secondary: '#0F766E',
    shade2: '#14B8A6',
    shade3: '#F0FDFA',
    decorations: 'crest',
  },
  {
    name: 'Vivid Emerald & Mint',
    primary: '#004D40',
    accent: '#00E676',
    paper: '#FFFFFF',
    secondary: '#00701A',
    shade2: '#00796B',
    shade3: '#E8F5E9',
    decorations: 'modern-accent',
  },
  {
    name: 'Ruby Red & Sunset Amber',
    primary: '#880E4F',
    accent: '#FF9100',
    paper: '#FFFFFF',
    secondary: '#AD1457',
    shade2: '#D81B60',
    shade3: '#FCE4EC',
    decorations: 'horizontal-lines',
  },
  {
    name: 'Vibrant Cyber Cyan & Blue',
    primary: '#006064',
    accent: '#00E5FF',
    paper: '#FFFFFF',
    secondary: '#00838F',
    shade2: '#00ACC1',
    shade3: '#E0F7FA',
    decorations: 'subtle-box',
  },
  {
    name: 'Royal Purple & Bright Gold',
    primary: '#4A148C',
    accent: '#FFA000',
    paper: '#FFFFFF',
    secondary: '#6A1B9A',
    shade2: '#8E24AA',
    shade3: '#F3E5F5',
    decorations: 'crest',
  },
  {
    name: 'Vivid Saturated Coral & Forest',
    primary: '#1B5E20',
    accent: '#FF6E40',
    paper: '#FFFFFF',
    secondary: '#2E7D32',
    shade2: '#43A047',
    shade3: '#E8F5E9',
    decorations: 'brackets',
  },
  {
    name: 'Charcoal Teal & Platinum',
    primary: '#1E293B',
    accent: '#14B8A6',
    paper: '#FFFFFF',
    secondary: '#334155',
    shade2: '#475569',
    shade3: '#F8FAFC',
    decorations: 'modern-accent',
  },
  {
    name: 'Sunset Glow Rose & Gold',
    primary: '#5C0632',
    accent: '#FFD700',
    paper: '#FFFFFF',
    secondary: '#900C3F',
    shade2: '#C70039',
    shade3: '#FDEDEC',
    decorations: 'crest',
  },
  {
    name: 'Bold Forest & Emerald Green',
    primary: '#065F46',
    accent: '#10B981',
    paper: '#FFFFFF',
    secondary: '#047857',
    shade2: '#059669',
    shade3: '#ECFDF5',
    decorations: 'horizontal-lines',
  },
  {
    name: 'Brilliant Amber Ochre & Espresso',
    primary: '#3E2723',
    accent: '#FF9100',
    paper: '#FFFFFF',
    secondary: '#4E342E',
    shade2: '#8D6E63',
    shade3: '#EFEBE9',
    decorations: 'corner-flourish',
  },
  {
    name: 'Bright Indigo & Hot Pink',
    primary: '#1E1B4B',
    accent: '#FF2E93',
    paper: '#FFFFFF',
    secondary: '#31102F',
    shade2: '#4F46E5',
    shade3: '#EEF2FF',
    decorations: 'subtle-box',
  },
  {
    name: 'Vivid Peacock Turquoise & Marigold',
    primary: '#004D40',
    accent: '#FFB300',
    paper: '#FFFFFF',
    secondary: '#00695C',
    shade2: '#00897B',
    shade3: '#E0F2F1',
    decorations: 'corner-flourish',
  },
  {
    name: 'Rich Amethyst & Neon Lime',
    primary: '#31102F',
    accent: '#76FF03',
    paper: '#FFFFFF',
    secondary: '#4A148C',
    shade2: '#6A1B9A',
    shade3: '#F5EEF8',
    decorations: 'modern-accent',
  },
  {
    name: 'Corporate Saturated Jade & Coral',
    primary: '#064E3B',
    accent: '#FF6E40',
    paper: '#FFFFFF',
    secondary: '#0F766E',
    shade2: '#14B8A6',
    shade3: '#F0FDFA',
    decorations: 'horizontal-lines',
  },
  {
    name: 'Premium Mahogany & Bronze Gold',
    primary: '#3E1C1F',
    accent: '#CD7F32',
    paper: '#FFFFFF',
    secondary: '#5C262B',
    shade2: '#8E3E43',
    shade3: '#FDEDEC',
    decorations: 'corner-flourish',
  },
  {
    name: 'Modern Teal & Solar Yellow',
    primary: '#006064',
    accent: '#FFD600',
    paper: '#FFFFFF',
    secondary: '#00838F',
    shade2: '#00ACC1',
    shade3: '#E0F7FA',
    decorations: 'brackets',
  },
  {
    name: 'Sunset Burgundy & Tangerine',
    primary: '#4A121A',
    accent: '#FF5722',
    paper: '#FFFFFF',
    secondary: '#7A1A25',
    shade2: '#D32F2F',
    shade3: '#FDF2F4',
    decorations: 'crest',
  },
  {
    name: 'Bold Dark Emerald & Lime',
    primary: '#064E3B',
    accent: '#84CC16',
    paper: '#FFFFFF',
    secondary: '#0F766E',
    shade2: '#14B8A6',
    shade3: '#F0FDFA',
    decorations: 'modern-accent',
  },
  {
    name: 'Vanguard Pine & Platinum Gold',
    primary: '#1B4332',
    accent: '#D4AF37',
    paper: '#FFFFFF',
    secondary: '#2D6A4F',
    shade2: '#40916C',
    shade3: '#D8F3DC',
    decorations: 'corner-flourish',
  },
  {
    name: 'Executive Slate & Tangerine',
    primary: '#27272A',
    accent: '#F97316',
    paper: '#FFFFFF',
    secondary: '#3F3F46',
    shade2: '#52525B',
    shade3: '#F4F4F5',
    decorations: 'subtle-box',
  },
];

export const HEADLINE_FONTS: Font[] = [
  { label: 'Serif (Classic - Georgia)',   stack: "Georgia, 'Times New Roman', serif" },
  { label: 'Serif (Elegant - Cambria)',   stack: "'Cambria', Georgia, serif" },
  { label: 'Serif (Palatino)',            stack: "'Palatino Linotype', 'Book Antiqua', Palatino, serif" },
  { label: 'Serif (Garamond)',            stack: "Garamond, Georgia, serif" },
  { label: 'Sans (Montserrat)',           stack: "'Montserrat', 'Segoe UI', sans-serif" },
  { label: 'Sans (Inter)',                 stack: "'Inter', -apple-system, sans-serif" },
  { label: 'Sans (Playfair Display)',     stack: "'Playfair Display', Georgia, serif" },
  { label: 'Sans (Merriweather)',         stack: "'Merriweather', Georgia, serif" },
  { label: 'Sans (Oswald)',               stack: "'Oswald', 'Arial Narrow', sans-serif" },
  { label: 'Sans (Roboto)',               stack: "'Roboto', 'Helvetica Neue', sans-serif" },
  { label: 'Sans (Lato)',                 stack: "'Lato', Arial, sans-serif" },
  { label: 'Sans (Poppins)',              stack: "'Poppins', sans-serif" },
  { label: 'Serif (Lora)',                stack: "'Lora', Georgia, serif" },
  { label: 'Sans (Fira Sans)',            stack: "'Fira Sans', sans-serif" },
  { label: 'Serif (PT Serif)',            stack: "'PT Serif', Georgia, serif" },
  { label: 'Serif (Crimson Text)',        stack: "'Crimson Text', Georgia, serif" },
  { label: 'Serif (Cinzel Elegance)',     stack: "'Cinzel', Georgia, serif" },
  { label: 'Mono (Inconsolata Modern)',   stack: "'Inconsolata', monospace" },
  { label: 'Sans (Raleway Clean)',        stack: "'Raleway', sans-serif" },
];

export const SHAPES: Array<'circle' | 'square' | 'hexagon' | 'shield' | 'octagon' | 'badge-ribbon' | 'waves'> = [
  'circle',
  'square',
  'hexagon',
  'shield',
  'octagon',
  'badge-ribbon',
  'waves'
];

export const LOGO_STYLES: Array<'classic' | 'typographic' | 'bordered' | 'shadow-badge'> = [
  'classic',
  'typographic',
  'bordered',
  'shadow-badge'
];

export const LOGO_STYLE_LABELS = {
  classic: 'Classic Shape',
  typographic: 'Typographic Minimal',
  bordered: 'Font with Border',
  'shadow-badge': 'Premium 3D Shadow',
};

export const GRID_STYLES: Array<'none' | 'dots' | 'lines' | 'repeated-name' | 'graph' | 'isometric' | 'crosses' | 'diagonal' | 'hexagonal' | 'music' | 'calligraphy' | 'stipple' | 'blueprint' | 'circuit'> = [
  'none',
  'dots',
  'lines',
  'repeated-name',
  'graph',
  'isometric',
  'crosses',
  'diagonal',
  'hexagonal',
  'music',
  'calligraphy',
  'stipple',
  'blueprint',
  'circuit'
];

export const GRID_STYLE_LABELS = {
  none: 'No Grid/Lines',
  dots: 'Faint Dot Grid',
  lines: 'Light Rule Lines',
  'repeated-name': 'Repeated Name Background',
  graph: 'Graph Paper Grid',
  isometric: 'Isometric Grid',
  crosses: 'Cross/Plus Marks',
  diagonal: 'Diagonal Stripes',
  hexagonal: 'Hexagon Grid',
  music: 'Music Sheet Staves',
  calligraphy: 'Calligraphy Guides',
  stipple: 'Stipple / Noise',
  blueprint: 'Blueprint Grid',
  circuit: 'Circuit Board Pattern'
};

export const PAD_LAYOUTS: Array<'canva-minimal-blue-gold' | 'canva-creative-corporate' | 'canva-medical-clean' | 'canva-bold-finance' | 'canva-organic-abstract' | 'canva-bento-modular' | 'canva-editorial-luxury' | 'canva-colorful-playful' | 'canva-tech-isometric'> = [
  'canva-minimal-blue-gold',
  'canva-creative-corporate',
  'canva-medical-clean',
  'canva-bold-finance',
  'canva-organic-abstract',
  'canva-bento-modular',
  'canva-editorial-luxury',
  'canva-colorful-playful',
  'canva-tech-isometric'
];

export const CARD_LAYOUTS: Array<'centered' | 'split' | 'sideband' | 'modern-split' | 'minimalist-right' | 'dark-accent' | 'shield-badge' | 'bento-grid' | 'diagonal-split' | 'retro-tech' | 'luxury-gold' | 'wave-abstract' | 'minimalist-centered' | 'asymmetrical-stripe' | 'executive-badge' | 'architectural-structure' | 'geometric-nodes' | 'vertical-editorial' | 'corporate-envelope' | 'freepik-corporate-blue' | 'canva-creative-wave' | 'modern-gradient-edge' | 'luxury-gold-foil' | 'startup-geometric' | 'law-firm-classic' | 'creative-agency-bold' | 'medical-clean-cross' | 'real-estate-arch' | 'hospitality-elegant'> = [
  'centered',
  'split',
  'sideband',
  'modern-split',
  'minimalist-right',
  'dark-accent',
  'shield-badge',
  'bento-grid',
  'diagonal-split',
  'retro-tech',
  'luxury-gold',
  'wave-abstract',
  'minimalist-centered',
  'asymmetrical-stripe',
  'executive-badge',
  'architectural-structure',
  'geometric-nodes',
  'vertical-editorial',
  'corporate-envelope',
  'freepik-corporate-blue',
  'canva-creative-wave',
  'modern-gradient-edge',
  'luxury-gold-foil',
  'startup-geometric',
  'law-firm-classic',
  'creative-agency-bold',
  'medical-clean-cross',
  'real-estate-arch',
  'hospitality-elegant'
];

export const PAD_LAYOUT_LABELS = {
  'canva-minimal-blue-gold': '1. Classic Gold & Emerald Center',
  'canva-creative-corporate': '2. Royal Heritage Monogram',
  'canva-medical-clean': '3. Executive Thin Slate Border',
  'canva-bold-finance': '4. Traditional Law Chambers',
  'canva-organic-abstract': '5. Bespoke Luxury Centered',
  'canva-bento-modular': '6. Modern Architectural Grid',
  'canva-editorial-luxury': '7. Vintage Charcoal Frame',
  'canva-colorful-playful': '8. Minimalist Fine Line',
  'canva-tech-isometric': '9. Premium Institutional Seal'
};

export const CARD_LAYOUT_LABELS = {
  centered: '1. Stacked Classic',
  split: '2. Right-top Ribbon',
  sideband: '3. Left Color Strip',
  'modern-split': '4. Asymmetric Columns',
  'minimalist-right': '5. Minimalist Right-Aligned',
  'dark-accent': '6. Inverted Accent Band',
  'shield-badge': '7. Floating Shield Emblem',
  'bento-grid': '8. Modern Bento Grid Card',
  'diagonal-split': '9. Dynamic Diagonal Split',
  'retro-tech': '10. Retro Tech Monospaced Card',
  'luxury-gold': '11. Ultra-Luxury Gold Border',
  'wave-abstract': '12. Modern Wave Accent Card',
  'minimalist-centered': '14. Ultra-Minimal Centered Accent',
  'asymmetrical-stripe': '15. Triple Stripe Asymmetrical',
  'executive-badge': '16. Executive Crest & Border',
  'architectural-structure': '17. Architectural Bold Frame',
  'geometric-nodes': '18. Connected Node Pattern Card',
  'vertical-editorial': '19. Vertical Editorial Typography Card',
  'corporate-envelope': '20. Corporate Diagonal Overlay Card',
  'freepik-corporate-blue': '21. Freepik Corporate Theme',
  'canva-creative-wave': '22. Canva Creative Wave',
  'modern-gradient-edge': '23. Modern Gradient Edge',
  'luxury-gold-foil': '24. Luxury Gold Foil',
  'startup-geometric': '25. Startup Geometric',
  'law-firm-classic': '26. Law Firm Classic',
  'creative-agency-bold': '27. Creative Agency Bold',
  'medical-clean-cross': '28. Medical Clean',
  'real-estate-arch': '29. Real Estate Arch',
  'hospitality-elegant': '30. Hospitality Elegant',
};

export const INDUSTRIES: Array<'corporate' | 'legal' | 'medical' | 'creative' | 'hospitality'> = [
  'corporate',
  'legal',
  'medical',
  'creative',
  'hospitality'
];

export const INDUSTRY_LABELS = {
  corporate: 'General Corporate / Trade',
  legal: 'Law Firm & Legal Advocate',
  medical: 'Medical, Clinic & Health',
  creative: 'Creative Design, Tech & IT',
  hospitality: 'Hospitality, Luxury & Retail',
};

export const TEXTURES: Array<'none' | 'linen' | 'vellum' | 'canvas' | 'watercolor' | 'parchment' | 'recycled' | 'felt' | 'laid' | 'kraft' | 'metallic' | 'speckled' | 'leather' | 'wood'> = [
  'none',
  'linen',
  'vellum',
  'canvas',
  'watercolor',
  'parchment',
  'recycled',
  'felt',
  'laid',
  'kraft',
  'metallic',
  'speckled',
  'leather',
  'wood'
];

export const TEXTURE_LABELS = {
  none: 'No Texture (Smooth)',
  linen: 'Subtle Linen',
  vellum: 'Soft Vellum',
  canvas: 'Fine Canvas',
  watercolor: 'Watercolor Paper',
  parchment: 'Antique Parchment',
  recycled: 'Recycled Paper',
  felt: 'Felt Woven',
  laid: 'Classic Laid',
  kraft: 'Kraft Paper',
  metallic: 'Subtle Metallic',
  speckled: 'Speckled Texture',
  leather: 'Fine Leather',
  wood: 'Wood Grain'
};

export const DEFAULT_COMPANY_DATA: CompanyData = {
  companyName: "Processing Hub",
  address: "34/D, Level-3, Jamuna Future Park, Vatara, Dhaka-1229",
  phone: "+8801332601510",
  email: "processinghubbd@gmail.com",
  tagline: "processinghubbd.com",
  empName: "MOHAMMAD NUR HASNAT",
  empRole: "Proprietor",
  empPhone: "+8801861186863",
  empEmail: "mohammadnurhasnat@gmail.com",
  empIdNumber: "PH-88026",
  casing: 'title',
  industry: 'corporate',
};
